workflows:
  ios-build-ipa:
    name: iOS Build IPA
    max_build_duration: 60
    environment:
      xcode: latest
    scripts:
      - name: Resolve Swift Packages
        script: |
          xcodebuild -resolvePackageDependencies

      - name: Build and Archive
        script: |
          xcodebuild \
            -project stepsCounter.xcodeproj \
            -scheme stepsCounter \
            -sdk iphoneos \
            -configuration Release \
            -archivePath $CM_BUILD_DIR/build/Training_Steps_Counter.xcarchive \
            archive

      - name: Export IPA
        script: |
          xcodebuild -exportArchive \
            -archivePath $CM_BUILD_DIR/build/Training_Steps_Counter.xcarchive \
            -exportOptionsPlist exportOptions.plist \
            -exportPath $CM_BUILD_DIR/build/ipa

    artifacts:
      - build/ipa/*.ipa
